---
title: My Curriculum Vitae
description: Professional CV with experience, education, research, and more
theme: jekyll-theme-minimal

collections:
  experience:
    output: true
    permalink: /experience/:name/
  education:
    output: true
    permalink: /education/:name/
  publications:
    output: true
    permalink: /publications/:name/
  thesis:
    output: true
    permalink: /thesis/:name/
  projects:
    output: true
    permalink: /projects/:name/
  opinion:
    output: true
    permalink: /opinion/:name/
  miscellaneous:
    output: true
    permalink: /miscellaneous/:name/

exclude:
  - README.md